name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t sabababa/assignment3:latest .

    - name: Push Docker Image to Dockerhub
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u sabababa --password-stdin
        docker push sabababa/assignment3:latest
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
